baseURL = "https://flutter.de/"
languageCode = "de-DE"
title = "Flutter Deutschland"
theme = "fluttery"
MetaDataFormat = "yaml"
DefaultContentLanguage = "de"
Paginate = 18 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-140814434-1"
enableRobotsTXT = true
enableEmoji = true
disqusShortname = "localhost"
uglyurls = true

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true

[permalinks]
  artikel = "artikel/:slug/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

# navigation
[menu]
  [[menu.main]]
  name = "Start"
  URL = "/"
  weight = 1
  
  [[menu.main]]
  name = "Artikel"
  URL = "artikel.html"
  weight = 2
  
 [[menu.main]]
   name = "Schulung"
   URL = "schulung/flutter-schulung.html"
   weight = 3

  [[menu.main]]
  name = "Community"
  URL = "community"
  weight = 4
  
    [[menu.main]]
    parent = "Community"
    name = "Meetups Deutschland"
    URL = "community/meetups.html"
    weight = 1
    
    # [[menu.main]]
    # parent = "Community"
    # name = "Experten Netzwerk"
    # URL = "community/experten-netzwerk-deutschland"
    # weight = 2
    
  [[menu.main]]
  parent = "Community"
  name = "Flutter CTO Guide"
  URL = "community/flutter-cto-guide.html"
  weight = 3

  [[menu.main]]
  name = "App Entwicklung"
  URL = "app-entwicklung-mit-flutter.html"
  weight = 5
  
  
    
    ##[[menu.main]]
    ##parent = "Schulung"
    ##name = "Flutter Schulung"
    ##URL = "schulung/flutter-schulung.html"
    ##weight = 1
    

[taxonomies]
  author = "authors"

# disableKinds = ["taxonomyTerm"]